### ISSUE TITLE
Exception when trying to start purescript in vscode

### ISSUE THREAD

**Issue by peteryhwong** [nwolverson/vscode-ide-purescript#112]
I have installed purescript as follows
* Pulp version 12.3.0
* purs version 0.12.0 using /usr/local/bin/purs
and ran the following commands in the terminal to initialise a skeleton Purescript project at `/Users/peter/Downloads/vscode-test-workspace/purescript-example` 
```
/Users/peter/Downloads/vscode-test-workspace/purescript-example : pulp init
/Users/peter/Downloads/vscode-test-workspace/purescript-example : pulp build
```
And now I have the following in the folder
```
/Users/peter/Downloads/vscode-test-workspace/purescript-example :ls -al
total 24
drwxr-xr-x  10 peter  staff   340 11 Aug 00:59 .
drwxr-xr-x   4 peter  staff   136 11 Aug 00:59 ..
-rw-r--r--   1 peter  staff   111 11 Aug 00:58 .gitignore
drwxr-xr-x   2 peter  staff    68 11 Aug 00:59 .pulp-cache
-rw-r--r--   1 peter  staff    15 11 Aug 00:58 .purs-repl
-rw-r--r--   1 peter  staff   323 11 Aug 00:59 bower.json
drwxr-xr-x   6 peter  staff   204 11 Aug 00:59 bower_components
drwxr-xr-x  51 peter  staff  1734 11 Aug 00:59 output
drwxr-xr-x   3 peter  staff   102 11 Aug 00:58 src
drwxr-xr-x   3 peter  staff   102 11 Aug 00:58 test
```
I have start vscode version 1.25.1 with workspace at `/Users/peter/Downloads/vscode-test-workspace` and installed PureScript IDE version 0.19.0.  Now I have the following folder:
```
/Users/peter/Downloads/vscode-test-workspace :ls -al
total 8
drwxr-xr-x     4 peter  staff    136 11 Aug 00:59 .
drwx------+ 1180 peter  staff  40120 10 Aug 14:47 ..
-rw-r--r--     1 peter  staff      5 11 Aug 00:59 .psc-ide-port
drwxr-xr-x    10 peter  staff    340 11 Aug 00:59 purescript-example
```
At loading Main.purs, I get the warning saying `Output directory does not exist at 'output'` and vscode asks me to build the project. The following is the output log
```
Launching new language client for file:///Users/peter/Downloads/vscode-test-workspace
[Function: effectiveOutputDirectory]
PureScript Language Server started
[Info  - 00:59:25] {"processId":53000,"rootPath":"/Users/peter/Downloads/vscode-test-workspace","rootUri":"file:///Users/peter/Downloads/vscode-test-workspace","capabilities":{"workspace":{"applyEdit":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true,"configuration":true},"textDocument":{"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true}},"hover":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true}}},"initializationOptions":{"executeCommandProvider":false},"trace":"off","workspaceFolders":[{"uri":"file:///Users/peter/Downloads/vscode-test-workspace","name":"vscode-test-workspace"}]}
Starting with cwd: /Users/peter/Downloads/vscode-test-workspace
Starting with args: ["/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","purescript-language-server","--node-ipc","--clientProcessId=53000"]
Activated lc for file:///Users/peter/Downloads/vscode-test-workspace
Got updated settings
[Info  - 00:59:25] Starting IDE server
handler onDocumentSymbol
handler onCodeAction
[Info  - 00:59:26] Resolved IDE server paths (npm-bin: false) from PATH of /usr/local/opt/redis@3.2/bin:/Users/peter/.rvm/gems/ruby-2.4.1/bin:/Users/peter/.rvm/gems/ruby-2.4.1@global/bin:/Users/peter/.rvm/rubies/ruby-2.4.1/bin:/usr/local/opt/php@7.0/sbin:/usr/local/opt/php@7.0/bin:/Users/peter/Library/Python/2.7/bin:/Users/peter/Documents/apps/gradle-3.5/bin:/Users/peter/Library/Android/sdk/tools:/Users/peter/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/peter/.rvm/bin:/usr/local/mysql/bin (1st is used):
[Info  - 00:59:26] /usr/local/bin/purs: 0.12.0

[Info  - 00:59:26] Starting IDE server on port 15936 with cwd /Users/peter/Downloads/vscode-test-workspace
Started IDE server (port 15936)
[Info  - 00:59:26] Parsed Options:
ServerOptions {_serverDirectory = Nothing, _serverGlobs = ["src/**/*.purs","bower_components/**/*.purs"], _serverOutputPath = "output", _serverPort = 15936, _serverNoWatch = False, _serverPolling = False, _serverLoglevel = LogDebug, _serverEditorMode = False}
Your output directory didn't exist. This usually means you didn't compile your project yet.
psc-ide needs you to compile your project (for example by running pulp build)
[Debug] Accepted a connection @(main:Command.Ide app/Command/Ide.hs:204:5)
[Debug] Received command: {"params":{"dependencies":[],"modules":[]},"command":"load"} @(main:Command.Ide app/Command/Ide.hs:214:9)

Onconfig: false
[Info  - 00:59:26] Output directory does not exist at 'output'
```
After I press build the purescript ide seems to have crashed with the following log (immediately after the line above:
```
[Info  - 01:01:11] Resolved build command (1st is used): 
[Info  - 01:01:11] /usr/local/bin/pulp: Pulp version 12.3.0
purs version 0.12.0 using /usr/local/bin/purs

/Users/peter/.vscode/extensions/nwolverson.ide-purescript-0.19.0/node_modules/purescript-language-server/server.js:2516
                  throw util.fromLeft(step);
                  ^

Error: Didn't find JSON output
    at Object.exports.error (/Users/peter/.vscode/extensions/nwolverson.ide-purescript-0.19.0/node_modules/purescript-language-server/server.js:3129:12)
    at __do (/Users/peter/.vscode/extensions/nwolverson.ide-purescript-0.19.0/node_modules/purescript-language-server/server.js:9977:113)
    at ChildProcess.<anonymous> (/Users/peter/.vscode/extensions/nwolverson.ide-purescript-0.19.0/node_modules/purescript-language-server/server.js:7264:52)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[Error - 01:01:11] Connection to server got closed. Server will not be restarted.
```

**Comment by nwolverson** [comment]
I saw this error, not sure where that `fromLeft` stuff comes from, it looks like the behaviour in this "Didn't find JSON output" case has changed at some point (saw this myself just today).

Can you ensure you're opening your purescript project (so in this example, `purescript-example`) as the/a root folder in vscode? It looks from glancing at the above that maybe you've opened the folder above it. It's fine to open multiple purescript projects in a vscode workspace, but they should be root folders.
