### ISSUE TITLE
error reporting not working in ubuntu

### ISSUE THREAD

**Issue by vishnuixm** [nwolverson/vscode-ide-purescript#22]
When we save the file we just sometimes get "Build Error :(" and no error reporting.

When we checked the Developer Tools, we were able to see ECONNREFUSED error.

Thanks in Advance for the fix.

**Comment by nwolverson** [comment]
I've seen this, I think either the psc-ide server has died or not started properly. In the interim you can probably remove `.psc-ide-port` (if present in project root) and reload the window.

**Comment by nwolverson** [comment]
I'm not particularly convinced I've fixed your issue, but can you try again with the latest version? I have fixed a couple of cases which would show this message

**Comment by vishnuixm** [comment]
@nwolverson sorry for the delay will check and get back to you,  thanks.

**Comment by vishnuixm** [comment]
@nwolverson  am still not getting the error messages.

**Comment by texastoland** [comment]
I've wished for a restart like `pscid` but it feels like a workaround.

**Comment by nwolverson** [comment]
I'm definitely going to add a restart psc-ide-server command, it's certainly useful -but if the issue is the server is dying for some reason, of course that is a problem.

There's not enough information to debug in this case, in particular I assume rebuild on save is enabled, was previously working, but at some point stops working and never starts working again - is that correct? Do you see one `ECONNREFUSED` per action (I assume)? Did you get tooltips etc initially but not once you see this sadface message?

Can you check if there is a `psc-ide-server` process running?

**Comment by vishnuixm** [comment]
@nwolverson Yes the psc-ide-server is running in the background and we are getting ECONNREFUSED for every save of .purs file. and we are getting "rebuild failed :(" message

**Comment by texastoland** [comment]
This doesn't like Ubuntu. I've been switching back and forth between `pscid` for the same reason. I can fire up Zoom this weekend for a group debug? I'd also like to get familiar with contributing.

**Comment by nwolverson** [comment]
@vishnuixm 

* What platform are you on?
* What version of psc-ide-server (should be per psc version, and is logged on startup of the extension)
* Are you running any other tool (eg pscid)?
* Can you check the port of the running `psc-ide-server` - does it match what was notified/logged on startup?
* Can you connect with `psc-ide-client` directly?
* Try the following:
  * Kill extension & `psc-ide-server`
  * `echo -n '1234' > .psc-ide-port` (in project dir)
  * `psc-ide-server --debug -p 1234` (in project dir)
  * Start extension and see if anything interesting turns up

As @texastoland says it would be easier to work thorough this and debug live. @texastoland sounds like a good idea,

**Comment by sudhirvkumar** [comment]
@nwolverson I can answer some of your questions on behalf of @vishnuixm  as we are on the same team and I was involved personally.

Platform is Ubuntu 14.04 LTS
psc-ide-server version is 0.9.3
No, we are not running any other tool like pscid
yes, the port of the psc-ide-server is matching with what is displayed when it vscode extension starts

We didn't try to connect with the psc-ide-client directly yet. Will try during our day and get back to you.

Will check the debug command and get back to you.

Some additional information might be useful....

We installed Atom and VS Code on 4 different developers machines

3 machines worked with VSCode with purescript extension yesterday. Today only one worked and 3 others didn't work. We tried checking again in the evening and one another machine also worked by showing the errors.

While on the same machines when we use Atom Editor and purescript ide and it just works fine!

Atom is slow... but works fine on the same machine... we would love to use VSCode with purescript.

I hope the above info helps

Will get back to you about the client and the debug info tomorrow.

**Comment by texastoland** [comment]
For comparison:

Platform: OS X
`psc-ide-server` version: 0.9.2
Other tools: `pscid` intermittently
Port matches: I don't think so?

```
[Extension Host] Found existing port from file: 15266, cwd: ~/Documents/Patch/purescript-localstorage
```
<details>
```
threadService.ts:214[Extension Host] Found psc-ide-server with correct path: ~/Documents/Patch/purescript-localstorage
threadService.ts:214[Extension Host] Resolved psc-ide-server:
threadService.ts:214[Extension Host] /usr/local/bin/psc-ide-server: 0.9.2
```
</details>
```
shell.ts:422connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:59756): Error: connect 
```
<details>
```
EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:59756)
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at connect (net.js:849:16)
    at net.js:984:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)e.onUnexpectedError @ shell.ts:422
```
</details>

Connect directly: `pscid` works (aside from my misunderstanding how it works)

> it would be easier to work thorough this and debug live.

I can schedule my weekend around it. The Zoom room is always open at the link on Meetup regardless!

**Comment by nwolverson** [comment]
@sudhirvkumar thanks for the info. Glad to hear the extension is being used, I think it's not really battle tested at the moment in the way the Atom package is.

One thing is this extension will try to use the same server that pscid/atom package use, if the `.psc-ide-port` file is present. A possibility is starting Atom, then starting Code, the Code extension will use the same server, then quitting Atom might kill the server it started.

For a clean test I'd remove `.psc-ide-port` if it exists, start Code on its own.

@texastoland those details are a red herring :(  The "found existing port" message does not mean that is the port that is used necessarily, if there's no further message the actual port must just be displayed in the info popup. And the `EADDRNOTAVAIL` I think not only happens normally (at least for me) but also the port noted I think is the client port.

**Comment by sudhirvkumar** [comment]
@nwolverson yes, I did think about that scenario.

We closed everything and started just Code and tried and we didn't get error notification. I understand that its not tested as much as the Atom extension... now we are testing it ;)

We love Code... just for the Speed ... and more...

**Comment by texastoland** [comment]
> those details are a red herring :(

My bad I'll keep track of the port at startup and console messages. The issue only started happening for me around when this was reported.

**Comment by texastoland** [comment]
I preemptively reinstalled the latest PureScript from npm globally (and deleted one in `node_modules`) prompted by #28 and no problems the last few hours.

**Comment by nwolverson** [comment]
@texastoland failure behaviour in #28 should be server errors on startup.

However the mention of global and `node_modules` - nothing is done to use bins from `node_modules`, so if you have mixed compiler versions by running a build with one version but `psc-ide-server` from a different version, maybe bad things could happen (but again I wouldn't expect this failure mode).

**Comment by texastoland** [comment]
It's almost certainly related. I haven't encountered the issue since (still going).

**Comment by nwolverson** [comment]
@texastoland any idea what version you might have had previously (locally and globally)? I'd like to try and reproduce

**Comment by texastoland** [comment]
I had `0.9.1` in `node_modules` but `0.9.2` `psc-ide-server` (I think global was up to date but I reinstalled anyway).

**Comment by sudhirvkumar** [comment]
There is a scenario where it is working...

1. I close everything and stop psc-ide-server if its running
2. Start Atom and open the current project and open a purs file to start the psc-ide-server
3. close all open files in Atom and minimize Atom
4. open VSCode
5. Code away!

Everything works as long as Atom is running in the background...

I am going to use that till its permanently solved in VSCode...

Thanks @nwolverson for your great work! :+1:
