### ISSUE TITLE
Failure to start unless c:\tmp directory exists

### ISSUE THREAD

**Issue by Savelenko** [nwolverson/vscode-ide-purescript#227]
Hello, 

Suddenly the IDE (or the language server, usure) fails to start when VS Code starts with the following message:

~~~
Error: ENOENT: no such file or directory, open 'c:\tmp\psc-ide-cmd.txt'
    at Object.writeFileSync (node:fs:2388:20)
    at Object.appendFileSync (node:fs:2469:6)
    at c:\Users\<user>\.vscode\extensions\nwolverson.ide-purescript-0.26.6\dist\server.js:35:121290
    at c:\Users\<user>\.vscode\extensions\nwolverson.ide-purescript-0.26.6\dist\server.js:35:6157
    at c:\Users\<user>\.vscode\extensions\nwolverson.ide-purescript-0.26.6\dist\server.js:35:6161
    at en (c:\Users\<user>\.vscode\extensions\nwolverson.ide-purescript-0.26.6\dist\server.js:35:34751)
    at Z (c:\Users\<user>\.vscode\extensions\nwolverson.ide-purescript-0.26.6\dist\server.js:35:36360)
    at c:\Users\<user>\.vscode\extensions\nwolverson.ide-purescript-0.26.6\dist\server.js:35:36468
    at ie (c:\Users\<user>\.vscode\extensions\nwolverson.ide-purescript-0.26.6\dist\server.js:35:34931)
    at Object.enqueue (c:\Users\<user>\.vscode\extensions\nwolverson.ide-purescript-0.26.6\dist\server.js:35:35068) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'c:\\tmp\\psc-ide-cmd.txt'
}

Node.js v20.18.1
[Error - 2:20:19 PM] Connection to server got closed. Server will not be restarted.
Didn't find workspace folder for file:///c%3A/Users/<user>/.vscode/extensions/nwolverson.ide-purescript-0.26.6/dist/server.js
~~~

Note the `c:\tmp` in the output. Everything works after I manually created this directory. However, I think the directory wasn't there before.

**Comment by nwolverson** [comment]
Uh that may be a temporary debugging edit that has escaped into the wild, this should not exist

**Comment by zeng-y-l** [comment]
I had this problem too.

**Comment by noncom** [comment]
Bump
+1

**Comment by Tuckertcs** [comment]
Also having this problem, and also solved it by manually creating the `C:\tmp` folder.

This should probably be fixed, as it results in the extension not failing to start.
