### ISSUE TITLE
Version 0.10 seems broken on Market

### ISSUE THREAD

**Issue by dfarmer** [nwolverson/vscode-ide-purescript#66]
I seem to have installed right at the same time that 0.10 was released, so I'm not sure if this isn't just a market issue but the extension seems to be completely broken for me on Windows 10. IDE server fails to start with: 
`Error: Cannot find module 'purescript-language-server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (C:\Users\dan_f\.vscode\extensions\nwolverson.ide-purescript-0.10.0\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:109:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pipe.onconnection (net.js:1454:8)
[Error - 11:42:31 AM] Connection to server got closed. Server will not be restarted.`

But also Purescript Build fails with "Command purescript.build not found"; purescript add import fails with "command purescript.addImport not found." Pretty obviously not a bug, but something seems to have gone wrong and as of now at least nothing works as installed from the market place.

**Comment by justinwoo** [comment]
I get this too on Windows, and if I npm global install `purescript-language-server` and run it, I get "The system cannot find the path specified."

**Comment by nwolverson** [comment]
As per #67, apologies. New version published which should resolve this issue.

**Comment by nwolverson** [comment]
@justinwoo you raise another valid issue, BTW, thanks for that comment around running directly `purescript-language-server`.
